services:
  - type: web
    name: rams-webapp
    env: python
    plan: free
    buildCommand: |
      cd frontend && yarn install && yarn build
        cd ../backend
      pip install -r backend/requirements.txt
    startCommand: "uvicorn backend.main:app --host 0.0.0.0 --port 8000"
    envVars:
      - key: JWT_SECRET
        value: change_me_securely

